[mypy]
# Equivalent to --check-untyped-defs
# This analyzes the body of functions without type annotations
check_untyped_defs = True

# Additional helpful strictness settings:
# Reports an error when a list or dictionary is initialized as empty 
# without an explicit type hint.
disallow_any_generics = True

# Disallows calling functions without type annotations from 
# functions with type annotations.
disallow_untyped_calls = True

# Warns about casting an expression to its own type.
warn_redundant_casts = True

# Warns when a # type: ignore comment is no longer needed.
warn_unused_ignores = True

# Shows a specific error code for each violation, 
# making it easier to silence specific errors.
show_error_codes = True
